version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - wpla4db_mongo_volume:/data/db

volumes:
  wpla4db_mongo_volume:
